const GAME_CONSTANTS = require('../../shared/game-constants');

const TICK_RATE = 30;
const SURVIVOR_SPEED = 160;

module.exports = {
  ...GAME_CONSTANTS,
  TICK_RATE,
  TICK_MS: 1000 / TICK_RATE,
  SURVIVOR_SPEED,
  HUNTER_SPEED: SURVIVOR_SPEED * 1.3,
  CARRY_SPEED_MULT: 0.7,
  INTERACTION_RANGE: 50,
  ATTACK_RANGE: 60,
  ATTACK_COOLDOWN_TICKS: TICK_RATE * 1,
  HUNTER_HP: 999,
  CIPHER_TOTAL: 5,
  CIPHER_DECODE_PER_TICK_PER_DECODER: 100 / (20 * TICK_RATE),
  RESCUE_PER_TICK_PER_RESCUER: 100 / (5 * TICK_RATE),
  CHAIR_COUNTDOWN_TICKS: TICK_RATE * 30,
  ELIMINATE_TARGET: 3,
  BROADCAST_INTERVAL_MS: 100,
  SPOTTED_RANGE: 200,
  COLLISION_RADIUS: 16,
  RANDOM_SPAWN_MARGIN: 50,
  RANDOM_SPAWN_ATTEMPTS: 200,
  CIPHER_SPAWN_MARGIN: 90,
  CIPHER_SPAWN_ATTEMPTS: 500,
  CIPHER_MIN_DISTANCE: 110,
  RESULT_STATUSES: new Set(['survivors_won', 'hunter_won']),
};
